services:
  db:
    container_name: mariadb
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - devops_devops
    environment:
      - MARIADB_USER=johnny
      - MARIADB_PASSWORD=s3cr4T
      - MARIADB_DATABASE=promocesi
      - MARIADB_ROOT_PASSWORD=sup4rs3cure

  backend:
    container_name: php
    image: ghcr.io/boris-picard/devops-cesi:latest
    ports:
      - "85:80"
    networks:
      - devops_devops
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.watchtower/config.json:/config.json
    environment:
      - DOCKER_CONFIG=/
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_DEBUG=true
      - WATCHTOWER_POLL_INTERVAL=5
      - WATCHTOWER_LABEL_ENABLE=true
    networks:
      - devops_devops

networks:
  devops_devops:
    external: true
