name: devops

on:
  push:
    branches:
      - "feat/**"
      - "dev"
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor  }}
          password: ${{ secrets.GHCR_PASSWORD }}

      - name: Build image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/devops-cesi:latest .

      - name: Push image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/devops-cesi:latest
